name: Building repository

on:
  push:
    branches: ["main"]
    # tags:
    #   - "*"
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_SULLY_URL: ${{ vars.VITE_SULLY_URL }}
          directory: .
          file_name: .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: use pnpm ${{ matrix.node-version }}
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Build
        run: |
          pnpm install
          pnpm build
